language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

env:
  global:
    PYTHONPATH=src:tests
    PYTHONUNBUFFERED=yes
    MANHOLE_TEST_TIMEOUT=30
  matrix:
    - WITH_COVERAGE=no 
    - WITH_COVERAGE=yes
    
before_install:
  - |
    if python --version |& grep PyPy; then
      deactivate
      sudo apt-add-repository --yes ppa:pypy/ppa
      sudo apt-get update
      sudo apt-get install pypy
      source ~/virtualenv/pypy/bin/activate
    fi
    python --version
    uname -a
    lsb_release -a
    sudo apt-get install strace
 
install: 
  - if [[ $WITH_COVERAGE == yes ]]; then pip install coverage coveralls; fi
  - python setup.py develop
  - sudo rmdir /dev/shm # see https://github.com/travis-ci/travis-core/issues/187
  - sudo ln -Tsf /{run,dev}/shm

script: 
  - python --version
  - rm .coverage* || true
  - stat /lib/x86_64-linux-gnu/libgcc_s.so.1
  - export LOG_NAME="$TRAVIS_PYTHON_VERSION-$TRAVIS_JOB_NUMBER-$TRAVIS_BUILD_ID.log"
  - |
    if [[ $WITH_COVERAGE == yes ]]; then
      #strace -f -s 8000 -o "$LOG_NAME"
      coverage run --source=src --parallel-mode tests/test_tblib.py
    else
      #strace -f -s 8000 -o "$LOG_NAME"
      python tests/test_tblib.py
    fi

after_failure:
  - curl -i -F "upfile=@$LOG_NAME" http://home.ionelmc.ro/

after_success:
  - coverage combine || true
  - coverage report --show-missing --include='src/*' || true
  - coveralls || true
